# Project information
site_name: Кодирование автомобилей VAG
site_description: Основные кодировки и адаптации платформ концерна VAG. Прошивки и параметрии. SWaP коды
site_author: Kanaduchi
site_url: http://www.vwcoding.ru

# Hot news
hot_news_date: 14.08.2021
hot_news_title: Все ваши предложения и новые идеи можно присылать на info@vwcoding.ru
hot_news: >
  1. <a href='https://vwcoding.ru/MQB/rearLights'>Задние динамические поворотники для Tiguan 2021 с фарами IQ Light</a><br>
  2. <a href='https://vwcoding.ru/MQB/pACC'>SWaP для ACC и pACC</a><br>
  3. <a href='https://vwcoding.ru/MQB/headDeviceTMC'>Активация TMC</a><br>
  4. <a href='https://vwcoding.ru/MQB/headDeviceFunctions'>SWaP коды и параметрия для ГУ CM и DM (F5 блок)</a><br>
  5. <a href='https://vwcoding.ru/MQB/headDeviceFunctionsPro'>SWaP коды и параметрия для ГУ PRO (F5 блок)</a><br>
  6. <a href='https://vwcoding.ru/MQB/2Q0_assistants.md'>Кодирование 2Q0* камеры ассистентов</a><br>

# Repository
repo_name: Kanaduchi/vwcoding
repo_url: https://github.com/Kanaduchi/vwcoding
edit_uri: https://github.com/Kanaduchi/vwcoding/edit/master/docs/

# Copyright
copyright: Copyright &copy; 2021 - vwcoding.ru (info@vwcoding.ru)

# Main directory
docs_dir: docs/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/icon.png
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Тёмная сторона
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Светлая сторона
  highlightjs: false
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top

extra_css:
  - assets/custom.css

plugins:
  - search:
      lang:
        - en
        - de
        - ru
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
  - print-site:
      add_to_navigation: false
      enumerate_headings: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Общая информация:
      - Кодирование автомобилей VAG: index.md
      - Платформа MQB: MQB/main.md
      - Платформа MLB-Evo: MLB-Evo/main.md
      - Платформа PQ26: PQ26/main.md
      - Платформа PQ35: PQ35/main.md
      - Калькулятор длинного кодирования: longCoding.md
      - Инструменты и адаптеры:
          - Список инструментов: programs.md
          - Инструкция ODIS E: odis-e.md
      - История изменений: history.md
      - Обратная связь: questions.md
      - Поддержать проект: https://yoomoney.ru/to/4100110582992748/100
  - Платформа MQB:
      - Информация: MQB/main.md
      - Ассистенты водителя:
          - Активация ACC и pACC: MQB/pACC.md
          - Кодирование ACC: MQB/ACC_coding.md
          - Кодирование 3Q* камеры: MQB/assistants.md
          - Кодирование 2Q* камеры: MQB/2Q0_assistants.md
          - Прошивки камеры ассистентов: MQB/camAssistFirmwares.md
      - Системы активной безопасности: MQB/active_systems.md
      - Движение и управление: MQB/drive.md
      - Парковка и маневрирование: MQB/parking.md
      - Эстетическая подсветка:
          - Кодирование подсветки: MQB/esteticLights.md
          - Кодирование зон освещения: MQB/esteticLightsCoding.md
          - Установка RGB подсветки: MQB/esteticLightsCodingRGB.md
      - Зеркала и стеклоочистители: MQB/wash.md
      - Отпирание и запирание: MQB/security.md
      - Освещение:
          - Кодирование фонарей: MQB/codingLights.md
          - Передние фонари:  MQB/headLights.md
          - Задние фонари: MQB/rearLights.md
      - Звук: MQB/sound.md
      - Климат: MQB/climate.md
      - Приборная панель: MQB/AID.md
      - Головное устройство:
        - Кодирование: MQB/headDevice.md
        - Активация TMC: MQB/headDeviceTMC.md
        - SWaP коды для CM и DM: MQB/headDeviceFunctions.md
        - Снятие защиты и SWaP для Pro: MQB/headDeviceFunctionsPro.md
      - Шины:
          - Кодирование: MQB/tires.md
          - Генератор параметрии: MQB/tiresCoding.md
      - Дооснащение: MQB/addons.md
  - Платформа MLB-Evo:
      - Информация: MLB-Evo/main.md
      - Ассистенты водителя: MLB-Evo/assistants.md
      - Движение и управление: MLB-Evo/drive.md
      - Безопасность. Отпирание и запирание: MLB-Evo/security.md
      - Комфорт: MLB-Evo/comfort.md
      - Климат: MLB-Evo/climate.md
      - Освещение: MLB-Evo/lights.md
      - Приборная панель: MLB-Evo/AID.md
      - Головное устройство: MLB-Evo/headDevice.md
  - Платформа PQ26:
      - Информация: PQ26/main.md
      - Освещение:
          - Управление освещением: PQ26/lights.md
          - Нестандартные световые решения: PQ26/extraLights.md
          - Обозначения ламп: PQ26/codingLights.md
          - Обозначения ламп c картинками: PQ26/codingLightsPictures.md
          - Установка светодиодов: PQ26/setLED.md
      - Стеклоочистители / Датчик дождя и света: PQ26/wash.md
      - Климат / Обогрев зеркал и стекол: PQ26/climate.md
      - Двери, стекла, цз, брелок и штатная сигнализация: PQ26/security.md
      - Панель приборов:
          - Кодирование: PQ26/instrPanel.md
          - Кривые подсветки панели приборов: PQ26/instrPanelCoding.md
      - Тормоза и шины: PQ26/brakes.md
      - Динамика и управление: PQ26/drive.md
      - Мультимедиа: PQ26/multimedia.md
      - Дооснащение: PQ26/addons.md
      - Словарь немецких терминов: PQ26/german.md
  - Платформа PQ35:
      - Информация: PQ35/main.md
      - Управление и динамика: PQ35/drive.md
      - Свет: PQ35/lights.md
      - Мультимедиа: PQ35/multimedia.md
      - Комфорт: PQ35/comfort.md
      - Прочие функции: PQ35/other.md
      - Кодирование Tiguan 1st Gen:
          - Управление и динамика: PQ35/Tiguan/drive.md
          - Комфорт: PQ35/Tiguan/comfort.md
          - Свет: PQ35/Tiguan/lights.md
          - Приборная панель: PQ35/Tiguan/instrPanel.md
          - Мультимедиа: PQ35/Tiguan/multimedia.md
  - Калькулятор длинного кодирования: longCoding.md
  - Поддержать проект: https://yoomoney.ru/to/4100110582992748/100